services:
  web:
    build: ./
    volumes:
       - ./src:/usr/src/app
    ports:
      - 80:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    command:
       sh -c 'npm run dev'
      #  sh -c 'npm run build && npm run start' # for production